### ISSUE TITLE
Use of kubeadm alpha config feature

### ISSUE THREAD

**Issue by jpmondet** [jpmondet/kubeadm-deployment-unleashed#1]
Would be cleaner to use the new feature allowing to use a config file instead of having zillions of flags on the init command line.

**Comment by jpmondet** [comment]
Example : 
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
 bindPort: 6443
networking:
 podSubnet: 10.0.1.0/24
kubernetesVersion: 1.9.3
nodeName: worker1
etcd:
 endpoints: 
 — http://etcd1
 — http://etcd2
 — http://etcd3
```
And then : 
`kubeadm init --config=file.yaml`
